### ISSUE TITLE
文章彈跳視窗『時間』與『內文』的間距

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/encore.frontend.web#1]
這是設計稿
<img width="972" alt="Screenshot 2023-12-15 at 10 39 19 PM" src="https://github.com/stephenchenorg/encore.frontend.web/assets/98463232/e083c52a-cde7-499f-a79d-2f3e829fb075">

這是切版
<img width="1285" alt="Screenshot 2023-12-15 at 10 24 12 PM" src="https://github.com/stephenchenorg/encore.frontend.web/assets/98463232/90acb72c-fda9-4e8c-8748-adcd01528efb">

**Comment by ycs77** [comment]
這個就是設計稿有小問題了。

![螢幕擷取畫面 (107)](https://github.com/stephenchenorg/encore.frontend.web/assets/38133356/cfddc924-5c22-42e9-9280-30b56fcf7b2e)

在設計稿中彈出視窗有兩份，一份是純設計 (design mode / dev mode)，一份是給 propotype 做模擬使用的。但他這個在兩個地方的間距是不同的，我是根據純設計那邊設定比較小的間距，其實也算是照設計稿來做的。

---

當然如果還是覺得不好看，我還是可以修。

**Comment by cindyvvg** [comment]
@ycs77 原來是設計稿本身不一致。
不過我覺得統一較好，且 25 px 的看起來較舒適，再麻煩你幫我統一成 25 px 的間距，感謝

**Comment by ycs77** [comment]
done
