### ISSUE TITLE
條件下沒有資料時，保留『找不到相關文章』的文字即可，下方列表頁請清空

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/encore.frontend.web#10]
當搜尋條件下（鎖定文章分類，或使用關鍵字搜尋）沒有符合的文章，出現『找不到相關文章』的文字即可，下方列表頁請清空

**Comment by ycs77** [comment]
![1703222137556](https://github.com/stephenchenorg/encore.frontend.web/assets/38133356/0fb0e565-f466-4cd5-86c1-542c275db4b2)

因為當時我是照這個調整的說...

呵呵呵

**Comment by ycs77** [comment]
> 當搜尋條件下（鎖定文章分類，或使用關鍵字搜尋）沒有符合的文章，出現『找不到相關文章』的文字即可，下方列表頁請清空

done

**Comment by cindyvvg** [comment]
@ycs77 sorry，抱歉..單純是業主的需求改變了，不是你的問題

**Comment by ycs77** [comment]
> @ycs77 sorry，抱歉..單純是業主的需求改變了，不是你的問題
> 

了解~ 😅
