### ISSUE TITLE
[ 手機版 ]文章頁面，下方的收藏與留言 icon 寬度需要滿版 

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/encore.frontend.web#3]
這是設計稿
<img width="416" alt="Screenshot 2023-12-15 at 10 34 55 PM" src="https://github.com/stephenchenorg/encore.frontend.web/assets/98463232/1b1194c5-88a3-4b85-bf64-baf78b8e9068">

這是切版
![IMG_1716](https://github.com/stephenchenorg/encore.frontend.web/assets/98463232/936ef7a6-04a9-4587-a670-c3b880f688b6)

**Comment by ycs77** [comment]
done
