### ISSUE TITLE
[ 手機版 ] 文章列表頁的文章代表圖，同電腦版一樣是長型的

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/encore.frontend.web#4]
這是設計稿
<img width="413" alt="image" src="https://github.com/stephenchenorg/encore.frontend.web/assets/98463232/806d60e9-d071-4661-87aa-a5aa96554117">

這是切版
![IMG_E8BAAB6EC7C9-1 2](https://github.com/stephenchenorg/encore.frontend.web/assets/98463232/a80f0e27-788a-4649-a7cf-696f0f6c1e2c)

還是是前端這邊有其他考量我們沒想到的？我可以提出跟業主討論

**Comment by ycs77** [comment]
不不不！這個「其他考量」是我沒想到的！

估計是 Safari 的問題，我的電腦、手機都不會出現此問題。

我已經推一個修復上去了，可以去看一下有沒有解決。

**Comment by cindyvvg** [comment]
測試 ok，感謝
![Uploading IMG_9386C8C2A3E3-1.jpeg…]()

**Comment by cindyvvg** [comment]
測試 ok，感謝
![IMG_9386C8C2A3E3-1](https://github.com/stephenchenorg/encore.frontend.web/assets/98463232/a0b8c84d-8bdc-4547-bad4-d1ee7087485d)
