### ISSUE TITLE
現在頁面上一直常駐著『找不到相關內容』的文字

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/encore.frontend.web#8]
不管切換類別，或搜尋關鍵字，列表頁上方都常駐著『找不到相關內容』的字
<img width="1662" alt="image" src="https://github.com/stephenchenorg/encore.frontend.web/assets/98463232/2216c1cc-845b-481f-ac36-a3c608763b06">

**Comment by ycs77** [comment]
要去新連結看

https://staging.encoredays.com/
