### ISSUE TITLE
大部分文章、右側安可廣告，點擊後的彈跳視窗都是空白

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/encore.frontend.web#9]
不確定目前是前端問題還是後端問題，麻煩前端這邊也幫忙確認
<img width="1710" alt="image" src="https://github.com/stephenchenorg/encore.frontend.web/assets/98463232/51f91ea4-189f-4142-adf5-fe614c891830">

**Comment by ycs77** [comment]
要去新連結看

https://staging.encoredays.com/
